version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INIT_ROOT_USERNAME: store
      MONGO_INIT_ROOT_PASSWORD: storeapi
    volumes:
      - mongodb-api:/data/db
    networks:
      - store-network
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: store
      ME_CONFIG_MONGODB_ADMINPASSWORD: storeapi
    networks:
      - store-network

  store-api:
    image: store-api:1.0
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGOURI: mongodb://store:storeapi@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - store-network

volumes:
  mongodb-api:
    driver: local

networks:
  store-network:
    driver: bridge