apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service
  mongo_uri: mongodb-service://username:password@mongo-service.default.svc.cluster.local:27017/mongodb