apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-api-deployment
  labels:
    app: store-api
spec:
  selector:
    matchLabels:
      app: store-api
  template:
    metadata:
      labels:
        app: store-api
    spec:
      containers:
      - name: store-api
        image: chetanguptaa/store-api:2.0
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: store-api-service
spec:
  type: NodePort
  selector:
    app: store-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30200

